### ISSUE TITLE
WSL 

### ISSUE THREAD

**Issue by marcmoraRAONA** [estruyf/vscode-spfx-localization#5]
Hi, there is some way to use this exetension in a WSL VSCode Environment? When I try to use, always appears:

Command 'SPFx create and insert localization key for selected text' resulted in an error (command 'extension.spfxLocalizationInsertKey' not found)

**Comment by estruyf** [comment]
Will need to test it out on a Windows machine.

**Comment by nbelyh** [comment]
I have tested and confirm the issue. The fix appears to be simple: you need to fix the casing for the module "localeKey.ts" (should be "LocaleKey.ts", with capital "L"). It simply cannot find the module (and therefore initialize the extension), because the names are case-sensitive.

To fix:
git mv --force ./src/commands/localeKey.ts ./src/commands/LocaleKey.ts
git commit -m "FIX WSL"

Fixed in branch:
https://github.com/nbelyh/vscode-spfx-localization/commits/fix_locale_key_wsl
At least I think so 😄 

@marcmoraRAONA would be great if you could check this later on

BTW, it seems that the issue also applies to any linux install (ubuntu in particular), not only WSL. 
Looks like on Mac and Windows it works fine because these two are not so strict regarding this?

**Comment by marcmoraRAONA** [comment]
OK perfect! I will check!

**Comment by marcmoraRAONA** [comment]
Yes It's OK. Now with this change , extension runs fine on WSL (Ubuntu)! 

Thanks!

**Comment by nbelyh** [comment]
@estruyf maybe include in the current release? It is just renaming the file basically.
Created PR:

**Comment by estruyf** [comment]
Will need to be in a new release. Didn't know if you were going to be that fast :-). Planning on other PRs?

**Comment by nbelyh** [comment]
I've pushed this in October... 😄 just forgot to create PR....

**Comment by estruyf** [comment]
New version `1.5.1` has now been published. Thanks @nbelyh!
